server:
  port: ":8080"
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "10s"
services:
  user_service_timeout: "10s"
  auth_service_timeout: "10s"
  book_service_timeout: "10s"
auth:
  session_life_time: "720h"
db:
  connection_string: "postgresql://postgres:postgres@localhost:5432/postgres"
  max_connections: 10
  min_connections: 1
  max_idle_time: "10m"
  max_lifetime: "1h"
s3:
  api_endpoint: "https://a690f12f89554b374e6de1008cf620a0.r2.cloudflarestorage.com"
  books_bucket: "test"
  access_key_id: "9bda3e60cd6e9b37d014e1724c8c6035"
  secret_key: "150a9e04ff8dcba84af1f5153e4898bca160bb44259c2fe61497220c0f26e704"
  token_value: "Qlp8lYOd1SNsw0CRxExoPUjlqzbX0AM9sFU9quKD"
  account_id: "a690f12f89554b374e6de1008cf620a0"
